spring:
  application:
    name: book-microservice-eureka
  profiles:
    active: dev

server:
  port: 8119

eureka:
  instance:
    hostname: book-microservice-eureka
    prefer-ip-address: false
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8119/eureka




