spring:
  application:
    name: book-zuul-gateway
  profiles:
    active: dev

server:
  port: 8139

eureka:
  instance:
    prefer-ip-address: true
    instance-id: bookzuul.com
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8119/eureka

zuul:
  prefix: /bk
  ignored-services: "*"
  routes:
    myticket:
      service-id: book-oauth-server
      path: /book-oauth-server/**

